SCOPE = "https://www.googleapis.com/auth/spreadsheets"
SPREADSHEET_ID = "1PjqMD8kJYjFSJduuX0rwor2Eej6O_qnjc5Ol81jG5T0"
SHEET_NAME = "dB"
GSHEET_URL = f"https://docs.google.com/spreadsheets/d/{SPREADSHEET_ID}"
TAB_RANGE = "A:J"
